export const projectsData = [
  {
    projectNumber: "01",
    projectName: "Florra AI",
    category: "AI-Powered Dating Assistant",
    description:
      "An intelligent assistant built within the Flutrr ecosystem to support matchmaking, conversation guidance, and personalized user engagement. The product combines AI workflows with a full-stack architecture to create a more contextual and helpful dating experience.",
    liveUrl: "#",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/74e928275_ChatGPTImageJun23202610_32_10PM.png",
    challenge: [
      "Build an AI-powered dating assistant from scratch within the existing Flutrr ecosystem.",
      "Deliver highly personalized and context-aware conversations for every user.",
      "Optimize AI response speed while orchestrating multiple backend services.",
      "Ensure consistent AI outputs despite varying prompts and user contexts.",
    ],
    scope: [
      "Build an AI assistant for matchmaking and conversation guidance.",
      "Support personalized recommendations using user context.",
      "Design scalable AI workflows and backend architecture.",
      "Deliver a seamless real-time conversational experience.",
    ],
    contributions: [
      "Designed the complete system architecture and AI workflows.",
      "Built the frontend, backend, APIs, and database architecture.",
      "Engineered prompt workflows and AI integrations.",
      "Managed deployment, testing, and production rollout.",
    ],
    impact: [
      "Increased new user signups by 20% through AI-powered engagement.",
      "Introduced AI capabilities into the Flutrr ecosystem.",
      "Improved matchmaking through personalized recommendations.",
      "Built a scalable foundation for future AI features.",
    ],
    role: "Lead Full Stack & AI Engineer",
    roleDescription:
      "Owned the full product build from architecture and AI logic to frontend and backend delivery.",
    impactMetric: "20%",
    impactDescription: "Signup lift through AI-driven engagement",
    contributionSummary: "Built From Scratch",
    contributionDescription:
      "Designed AI workflows, integrated backend services, and delivered the complete user experience independently.",
    techStack: [
      { name: "React.js", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "OpenAI", color: "#A78BFA", bg: "#0D1B2A" },
      { name: "Node.js", color: "#339933", bg: "#0D1B2A" },
      { name: "MongoDB", color: "#47A248", bg: "#0D1B2A" },
    ],
    highlights: [
      "Built context-aware conversational assistance for users",
      "Developed personalized matchmaking recommendation workflows",
      "Engineered real-time AI interaction support",
      "Delivered the product independently from architecture to deployment",
    ],
    illustration: "orb",
  },
  {
    projectNumber: "02",
    projectName: "Flutrr Official Website",
    glowPosition: "65% center",
    category: "Responsive Brand Website",
    description:
      "A production-ready marketing website built to strengthen Flutrr's online presence and improve product visibility. The site was designed to feel polished, fast, and consistent across desktop and mobile screens.",
    liveUrl: "https://flutrr.com/",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/b6c97ddbf_ChatGPTImageJun24202612_34_43PM.png",
    challenge: [
      "Deliver a production-ready website within a tight launch timeline.",
      "Maintain responsive consistency across all screen sizes.",
      "Optimize performance without sacrificing visual quality.",
      "Coordinate implementation across product, design, and engineering teams.",
    ],
    scope: [
      "Build Flutrr's official marketing website.",
      "Create a responsive and high-performance experience.",
      "Improve user acquisition and product awareness.",
      "Deliver a scalable production-ready platform.",
    ],
    contributions: [
      "Led frontend implementation and responsive development.",
      "Built reusable landing page components.",
      "Optimized website performance and SEO readiness.",
      "Collaborated throughout launch and deployment.",
    ],
    impact: [
      "Delivered the website ahead of schedule.",
      "Strengthened Flutrr's digital presence.",
      "Improved product visibility and acquisition experience.",
      "Established a scalable marketing platform.",
    ],
    role: "Frontend Developer",
    roleDescription:
      "Led the frontend implementation and helped deliver the website within a tight timeline.",
    impactMetric: "100%",
    impactDescription: "Responsive across desktop, tablet, and mobile",
    contributionSummary: "Launch Delivery",
    contributionDescription:
      "Built the responsive landing experience, optimized performance, and supported cross-functional launch execution.",
    techStack: [
      { name: "Next.js", color: "#ffffff", bg: "#000000" },
      { name: "React.js", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "TypeScript", color: "#3178C6", bg: "#0D1B2A" },
      { name: "Tailwind CSS", color: "#38BDF8", bg: "#0D1B2A" },
    ],
    highlights: [
      "Built a fully responsive marketing website",
      "Optimized load speed and visual consistency",
      "Helped deliver the site ahead of schedule",
      "Improved acquisition readiness through a cleaner web presence",
    ],
    illustration: "brain",
  },
  {
    projectNumber: "03",
    projectName: "Glodobaara",
    glowPosition: "55% center",
    category: "E-Commerce Mobile App",
    description:
      "A seamless shopping experience with a clean interface, secure payments, and personalized recommendations. The product was designed to feel intuitive and accessible while supporting core shopping flows end to end.",
    liveUrl: "#",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/5d4dfc8b2_ChatGPTImageJun24202601_25_24PM.png",
    challenge: [
      "Design intuitive interfaces for senior citizens with varying digital literacy.",
      "Build accessible experiences without increasing interface complexity.",
      "Handle reliable API integration and frontend data management.",
      "Ensure consistent performance across Android and iOS devices.",
    ],
    scope: [
      "Build an accessible mobile application for senior citizens.",
      "Prioritize readability and simplified navigation.",
      "Integrate backend APIs into mobile workflows.",
      "Deliver a cross-platform mobile experience.",
    ],
    contributions: [
      "Built reusable React Native components and screens.",
      "Integrated frontend applications with backend APIs.",
      "Improved accessibility through user-focused interface design.",
      "Collaborated within Agile development cycles.",
    ],
    impact: [
      "Built 10+ reusable React Native components.",
      "Reduced API response times by 34%.",
      "Reduced bounce rates by 20%.",
      "Reduced frontend defects by 25%.",
    ],
    role: "Full Stack Developer",
    roleDescription: "Designed and built the mobile app with end-to-end functionality.",
    impactMetric: "40%",
    impactDescription: "Improvement in dashboard performance and shopping flow",
    contributionSummary: "End-to-End Execution",
    contributionDescription:
      "Built the mobile experience, integrated backend services, and optimized the UI for performance and usability.",
    techStack: [
      { name: "React Native", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "Next.js", color: "#ffffff", bg: "#000000" },
      { name: "Node.js", color: "#339933", bg: "#0D1B2A" },
      { name: "MongoDB", color: "#47A248", bg: "#0D1B2A" },
      { name: "Redux", color: "#764ABC", bg: "#0D1B2A" },
      { name: "Stripe", color: "#635BFF", bg: "#0D1B2A" },
      { name: "AWS S3", color: "#FF9900", bg: "#232F3E" },
    ],
    highlights: [
      "Built a responsive and intuitive shopping experience",
      "Implemented secure checkout and payment integration",
      "Developed real-time order tracking and notifications",
      "Optimized performance for speed and scalability",
    ],
    illustration: "stack",
  },
  {
    projectNumber: "04",
    projectName: "Homi AI",
    category: "AI Marketing Assistant",
    description:
      "A multi-channel AI content platform that helps businesses generate marketing copy across Instagram, LinkedIn, blogs, email campaigns, and other brand assets. The focus was on speed, consistency, and quality across different content formats and tones.",
    liveUrl: "#",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/f7d491bef_ChatGPTImageJun24202601_06_18PM.png",
    glowPosition: "55% center",
    challenge: [
      "Generate high-quality content across multiple platforms and content formats.",
      "Maintain brand consistency across AI-generated outputs.",
      "Optimize AI workflows while minimizing response latency.",
      "Coordinate delivery across engineering, design, and product teams.",
    ],
    scope: [
      "Build an AI-powered marketing assistant.",
      "Support social media, blogs, emails, and marketing assets.",
      "Enable campaign management workflows.",
      "Deliver a scalable AI content platform.",
    ],
    contributions: [
      "Led product architecture and technical decisions.",
      "Designed AI content generation workflows.",
      "Coordinated engineering delivery and roadmap execution.",
      "Oversaw frontend, backend, and AI integrations.",
    ],
    impact: [
      "Streamlined multi-channel content creation.",
      "Reduced manual marketing effort.",
      "Improved campaign productivity through AI.",
      "Centralized marketing workflows into one platform.",
    ],
    role: "Project Head",
    roleDescription:
      "Led product direction, architecture decisions, and delivery across the full build cycle.",
    impactMetric: "Multi-Channel",
    impactDescription: "Content generation across marketing channels from one workflow",
    contributionSummary: "Product Strategy",
    contributionDescription:
      "Shaped the content workflows, coordinated stakeholders, and guided execution across frontend, backend, and AI layers.",
    techStack: [
      { name: "Next.js", color: "#ffffff", bg: "#000000" },
      { name: "React", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "TypeScript", color: "#3178C6", bg: "#0D1B2A" },
      { name: "Node.js", color: "#339933", bg: "#0D1B2A" },
      { name: "OpenAI", color: "#A78BFA", bg: "#0D1B2A" },
    ],
    highlights: [
      "Supported Instagram, LinkedIn, blog, and email content generation",
      "Built campaign-oriented content workflows",
      "Designed a centralized dashboard for marketing operations",
      "Improved consistency across platform-specific content formats",
    ],
    illustration: "orb",
  },
  {
    projectNumber: "05",
    projectName: "Rasoi",
    category: "Restaurant Operations Platform",
    description:
      "A real-time restaurant management system with four role-based dashboards for customers, waiters, kitchen staff, and owners. It digitizes the full dine-in journey from OTP login and ordering to billing, reviews, and table reset.",
    liveUrl: "https://resturant-dashboard-green.vercel.app",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/9738a4afa_ChatGPTImageJun24202608_37_22PM.png",
    challenge: [
      "Build a complete restaurant workflow supporting four user roles.",
      "Synchronize live updates across customers, waiters, kitchen, and owners.",
      "Design secure authentication and role-based access control.",
      "Manage complex order lifecycle and billing workflows.",
    ],
    scope: [
      "Digitize the complete dine-in experience.",
      "Build role-based dashboards for restaurant operations.",
      "Enable real-time order synchronization.",
      "Deliver analytics, billing, and operational reporting.",
    ],
    contributions: [
      "Designed the complete system architecture and database.",
      "Built all four dashboards and backend workflows.",
      "Implemented authentication, realtime updates, and analytics.",
      "Managed deployment, testing, and production delivery.",
    ],
    impact: [
      "Built 4 interconnected dashboards.",
      "Digitized the complete restaurant workflow.",
      "Enabled real-time collaboration across all stakeholders.",
      "Delivered actionable analytics for restaurant owners.",
    ],
    role: "Full Stack Engineer",
    roleDescription:
      "Built the architecture, workflows, dashboards, and realtime synchronization layer.",
    impactMetric: "Live Order Sync",
    impactDescription: "Real-time coordination across the full dine-in workflow",
    contributionSummary: "Workflow Ownership",
    contributionDescription:
      "Designed the database, built the dashboards, and implemented order lifecycle logic across all roles.",
    techStack: [
      { name: "Next.js", color: "#ffffff", bg: "#000000" },
      { name: "React", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "TypeScript", color: "#3178C6", bg: "#0D1B2A" },
      { name: "Supabase", color: "#3ECF8E", bg: "#0D1B2A" },
      { name: "PostgreSQL", color: "#336791", bg: "#0D1B2A" },
      { name: "Zustand", color: "#8B5CF6", bg: "#0D1B2A" },
    ],
    highlights: [
      "Built four dashboards: Customer, Waiter, Kitchen, and Owner",
      "Managed the full order lifecycle from pending to review",
      "Added real-time updates across orders, tables, and billing",
      "Helped owners track revenue, dishes, and staff performance",
    ],
    illustration: "stack",
  },
  {
    projectNumber: "06",
    projectName: "Bloomkeep",
    category: "Digital Gifting Platform",
    description:
      "A warm, mobile-first digital bouquet experience for sending personalized flowers when you cannot hand-deliver them. Users can build, customize, and share a living bouquet through a no-signup flow with music, animation, and a public reveal page.",
    liveUrl: "https://bloomloop-brown.vercel.app/",
    heroImage:
      "https://media.base44.com/images/public/6a2a6bb22076cf135bcee9e0/36ace0462_ChatGPTImageJun24202608_46_49PM.png",
    challenge: [
      "Create an emotional gifting experience without requiring user accounts.",
      "Support personalized bouquet creation with a simple user journey.",
      "Design backend logic for freshness tracking and event management.",
      "Build a scalable architecture for future monetization.",
    ],
    scope: [
      "Build a no-signup digital bouquet platform.",
      "Support bouquet customization, sharing, and music.",
      "Track bouquet interactions and freshness.",
      "Create a public gallery for shared bouquets.",
    ],
    contributions: [
      "Built the complete frontend and backend architecture.",
      "Developed bouquet builder and recipient reveal experiences.",
      "Implemented REST APIs, event tracking, and freshness logic.",
      "Designed scalable database and sharing workflows.",
    ],
    impact: [
      "Built a 4-step bouquet creation experience.",
      "Created a 12-flower digital gifting library.",
      "Delivered a complete no-signup gifting workflow.",
      "Engineered scalable backend event tracking.",
    ],
    role: "Full Stack Engineer",
    roleDescription:
      "Designed and built the end-to-end product, including the bouquet builder, recipient reveal experience, and backend event system.",
    impactMetric: "No-Signup Flow",
    impactDescription: "Complete gifting journey without account creation",
    contributionSummary: "Product + Backend Ownership",
    contributionDescription:
      "Built the 4-step bouquet flow, shareable bouquet links, living freshness logic, public gallery, and REST API architecture.",
    techStack: [
      { name: "Next.js", color: "#ffffff", bg: "#000000" },
      { name: "React", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "TypeScript", color: "#3178C6", bg: "#0D1B2A" },
      { name: "Express", color: "#339933", bg: "#0D1B2A" },
      { name: "Prisma", color: "#2D3748", bg: "#0D1B2A" },
      { name: "Supabase", color: "#3ECF8E", bg: "#0D1B2A" },
    ],
    highlights: [
      "Built a 4-step bouquet builder with arrangement, card, preview, and music selection",
      "Created a 12-flower library with preset arrangements and greenery variants",
      "Designed a tap-to-reveal recipient experience with ambient audio",
      "Implemented freshness decay, watering logic, and public opt-in gallery tracking",
    ],
    illustration: "orb",
  },
  {
    projectNumber: "07",
    projectName: "ChronoBook",
    category: "Smart Scheduling Platform",
    description:
      "A Calendly-style scheduling product with public booking pages, conflict detection, and automated confirmations. Hosts can manage availability and meeting types, while invitees book directly through a shareable link without creating an account.",
    liveUrl: "https://slotbookingchronebook.vercel.app/",
    heroImage: "/images/chronobook-detail.png",
    glowPosition: "55% center",
    challenge: [
      "Build a scheduling platform supporting multiple user roles.",
      "Prevent booking conflicts across dynamic availability.",
      "Integrate video meetings and transactional emails.",
      "Deliver a seamless booking experience without invitee accounts.",
    ],
    scope: [
      "Build a complete appointment scheduling platform.",
      "Support public booking through shareable links.",
      "Automate booking confirmations and reminders.",
      "Provide host and admin management dashboards.",
    ],
    contributions: [
      "Built the booking engine and host dashboard.",
      "Implemented slot conflict detection and booking lifecycle.",
      "Integrated email notifications and video meeting providers.",
      "Developed authentication and role-based workflows.",
    ],
    impact: [
      "Developed 30+ REST API endpoints.",
      "Enabled secure no-signup appointment booking.",
      "Automated confirmations, cancellations, and rescheduling.",
      "Built scalable scheduling infrastructure supporting multiple user roles.",
    ],
    role: "Full Stack Developer",
    roleDescription:
      "Built the host dashboard, public booking flow, booking lifecycle, and notification system.",
    impactMetric: "30+",
    impactDescription: "REST API endpoints powering the booking platform",
    contributionSummary: "Booking Engine",
    contributionDescription:
      "Implemented the public booking journey, conflict-safe slot selection, email notifications, and video-link fallback logic.",
    techStack: [
      { name: "React", color: "#61DAFB", bg: "#0D1B2A" },
      { name: "FastAPI", color: "#009688", bg: "#0D1B2A" },
      { name: "MongoDB", color: "#47A248", bg: "#0D1B2A" },
      { name: "TypeScript", color: "#3178C6", bg: "#0D1B2A" },
      { name: "Tailwind CSS", color: "#38BDF8", bg: "#0D1B2A" },
    ],
    highlights: [
      "Built a no-signup public booking flow for invitees",
      "Added slot conflict detection to prevent double-booking",
      "Enabled confirmations, cancellations, and rescheduling flows",
      "Designed host and admin dashboards for complete scheduling control",
    ],
    illustration: "stack",
  },
];
